image: golang:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - gofmt -w .
    - go build cmd/app/main.go

test_range:
  stage: test
  image: golang:latest
  script:
    - go test ./pkg/range -v

test_bank:
  stage: test
  image: golang:latest
  script:
    - go test ./pkg/bank -v