image: golang:latest

stages:
  - build
  - test

before_script:
  - go get golang.org/x/sync/errgroup

build:
  stage: build
  script:
    - gofmt -w .
    - go build cmd/app/main.go

test_mark:
  stage: test
  image: golang:latest
  script:
    - go test ./pkg/fact -v
